# Generated by Django 4.2.12 on 2024-05-08 21:40

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('prompt', models.TextField()),
                (
                    'som_neurons',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.FloatField(), size=128
                        ),
                        size=6,
                    ),
                ),
                ('authored_at', models.DateTimeField(null=True)),
                (
                    'authored_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SpellCast',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('echoing', 'Echoing'),
                            ('embedding', 'Embedding'),
                            ('error', 'Error'),
                            ('done', 'Exited'),
                        ],
                        max_length=10,
                    ),
                ),
                ('spell', models.TextField()),
                ('spell_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('echo', models.TextField()),
                (
                    'embedding',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=128
                    ),
                ),
                (
                    'direction',
                    models.IntegerField(
                        choices=[
                            (0, 'up'),
                            (1, 'up/right'),
                            (2, 'down/right'),
                            (3, 'down'),
                            (4, 'down/left'),
                            (5, 'up/left'),
                        ]
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='labirynth.player',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='labirynth.room'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_room',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='labirynth.room',
            ),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(
                fields=('x', 'y', 'z'), name='unique_coords'
            ),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(
                check=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            models.F('x'), '+', models.F('y')
                        ),
                        '+',
                        models.F('z'),
                    ),
                    '=',
                    models.Value(0),
                    output_field=models.BooleanField(),
                ),
                name='hex_grid',
            ),
        ),
    ]
