# Generated by Django 4.2.14 on 2024-07-24 18:52

import uuid

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('zoom_level', models.SmallIntegerField(default=0)),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('zoom_level', 'x', 'y', 'z'), name='unique_coords'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('x'), '+', models.F('y')), '+', models.F('z')), '=', models.Value(0), output_field=models.BooleanField()), name='hex_grid'),
        ),
    ]
