# Generated by Django 5.2.7 on 2025-10-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labirynth', '0002_roomversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomversion',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomversion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomVersion',
        ),
    ]
