name: Setup Python and Poetry dependencies
description: Install Python, Poetry, and project dependencies

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install
      shell: bash

    - name: Set up .env
      run: cp example.env .env
      shell: bash
