[tool.poetry]
name = "prompt-wars"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.4"
django = "==4.2.*"
openai = "^1.11.0"
django-environ = "^0.11.2"
psycopg = "^3.1.17"
django-recaptcha = "^4.0.0"
django-q2 = "^1.6.1"
sentry-sdk = {extras = ["django"], version = "^1.40.1"}
gunicorn = "^21.2.0"
whitenoise = "^6.6.0"
anthropic = "^0.20.0"
numpy = "*"
scipy = "*"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
flake8-isort = "^6.1.1"
pylint = "^3.0.3"
pytest = "^8.0.0"
pytest-django = "^4.8.0"
pylint-django = "^2.5.5"
flake8-pyproject = "^1.2.3"
factory-boy = "^3.3.0"
freezegun = "^1.4.0"
aider-chat = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
ignore = [
    "E501",  # line too long
]

[tool.isort]
skip_gitignore = true
lines_after_imports = 2
# 5 = Hanging Grid Grouped
multi_line_output = 5
include_trailing_comma = true

[tool.pylint.format]
recursive = "yes"
errors-only = "yes"
load-plugins = [
    "pylint_django",
]

[tool.pylint.pylint_django]
django-settings-module = "llm_wars.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "llm_wars.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
FAIL_INVALID_TEMPLATE_VARS = true
addopts = "--reuse-db"

[tool.black]
skip-string-normalization = true
