# Generated by Django 4.2.14 on 2024-08-18 18:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('generated_goal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_chunk', to='django_goals.goal')),
                ('previous_chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_chunks', to='stories.chunk')),
            ],
        ),
    ]
