# Generated by Django 5.2.7 on 2025-10-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
