# Generated by Django 4.2.17 on 2025-02-02 13:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
