# Generated by Django 4.2.10 on 2024-02-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warrior',
            name='moderation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrior',
            name='moderation_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warrior',
            name='moderation_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='next_battle_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='warrior',
            index=models.Index(
                condition=models.Q(('next_battle_schedule__isnull', False)),
                fields=['next_battle_schedule'],
                name='next_battle_schedule_index',
            ),
        ),
    ]
