# Generated by Django 4.2.10 on 2024-02-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0002_warrior_games_played_warrior_moderation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warrior',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='warrior',
            name='moderation_flagged',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='warrior',
            index=models.Index(
                condition=models.Q(('moderation_flagged', False)),
                fields=['rating'],
                name='rating_index',
            ),
        ),
    ]
