# Generated by Django 4.2.10 on 2024-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0003_alter_warrior_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='warrior_1_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='warrior_2_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
