# Generated by Django 4.2.10 on 2024-02-08 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0004_alter_battle_warrior_1_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrior',
            old_name='moderation_flagged',
            new_name='moderation_passed',
        ),
        migrations.RunSQL(
            'UPDATE warriors_warrior SET moderation_passed = not moderation_passed;',
        ),
    ]
