# Generated by Django 4.2.10 on 2024-02-09 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0005_rename_moderation_flagged_warrior_moderation_passed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ('-rating_transferred_at', '-scheduled_at')},
        ),
    ]
