# Generated by Django 4.2.10 on 2024-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0006_alter_battle_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warrior',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'body_sha_256',
                        models.Func(
                            models.Func(
                                models.F('body'),
                                models.Value('utf-8'),
                                function='convert_to',
                            ),
                            function='sha256',
                        ),
                    )
                ),
                name='body_sha_256',
            ),
        ),
    ]
