# Generated by Django 4.2.10 on 2024-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0007_warrior_body_sha_256'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='lcs_len_1_2_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='lcs_len_1_2_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='lcs_len_2_1_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='lcs_len_2_1_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
