# Generated by Django 4.2.10 on 2024-02-13 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0009_alter_warrior_author_alter_warrior_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='warrior_1_rating',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='warrior_2_rating',
        ),
    ]
