# Generated by Django 4.2.10 on 2024-02-13 20:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warriors', '0010_remove_battle_warrior_1_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrior',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='warrior',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='WarriorUserPermission',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'warrior',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='warriors.warrior',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='warrioruserpermission',
            constraint=models.UniqueConstraint(
                fields=('warrior', 'user'), name='warrior_user_unique'
            ),
        ),
        migrations.AddField(
            model_name='warrior',
            name='users',
            field=models.ManyToManyField(
                related_name='warriors',
                through='warriors.WarriorUserPermission',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
