# Generated by Django 4.2.10 on 2024-02-14 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'warriors',
            '0011_rename_author_warrior_author_name_warrior_created_by_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='scheduled_at',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
