# Generated by Django 4.2.10 on 2024-02-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0012_alter_battle_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='rating_error',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
