# Generated by Django 4.2.10 on 2024-02-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0013_warrior_rating_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='finish_reason_1_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='battle',
            name='finish_reason_2_1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
