# Generated by Django 4.2.10 on 2024-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0014_battle_finish_reason_1_2_battle_finish_reason_2_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='lcs_len_1_2_1',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='lcs_len_1_2_2',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='lcs_len_2_1_1',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='lcs_len_2_1_2',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
