# Generated by Django 4.2.10 on 2024-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0015_alter_battle_lcs_len_1_2_1_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warrior',
            name='rating_index',
        ),
        migrations.AddIndex(
            model_name='warrior',
            index=models.Index(
                condition=models.Q(('moderation_passed', True)),
                fields=['rating'],
                name='rating_index',
            ),
        ),
    ]
