# Generated by Django 4.2.10 on 2024-02-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0017_arena_battle_arena_warrior_arena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='arena',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='warriors.arena'
            ),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='arena',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='warriors.arena'
            ),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='body_sha_256',
            field=models.BinaryField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='warrior',
            constraint=models.UniqueConstraint(
                fields=('arena_id', 'body_sha_256'), name='arena_body_sha_256_unique'
            ),
        ),
    ]
