# Generated by Django 4.2.10 on 2024-02-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warriors', '0018_alter_battle_arena_alter_warrior_arena_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warrior',
            constraint=models.CheckConstraint(
                condition=models.Q(('rating_error__gte', 0.0)),
                name='rating_error_non_negative',
            ),
        ),
    ]
