# Generated by Django 4.2.10 on 2024-03-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('warriors', '0019_warrior_rating_error_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
