# Generated by Django 4.2.10 on 2024-03-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0021_arena_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
