# Generated by Django 4.2.10 on 2024-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0022_arena_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
