# Generated by Django 4.2.10 on 2024-03-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0023_arena_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrioruserpermission',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
