# Generated by Django 4.2.12 on 2024-06-07 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0024_warrioruserpermission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='rating_playstyle',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=list,
                size=2,
            ),
        ),
    ]
