# Generated by Django 4.2.16 on 2024-09-08 22:32

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0028_warrior_public_battle_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('warrior_count', models.PositiveIntegerField()),
                ('battle_count', models.PositiveIntegerField()),
                ('rating_quantiles', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='i-th element is the rating of the i-th percentile', size=101)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='warrior',
            name='rating_index',
        ),
        migrations.AddIndex(
            model_name='warrior',
            index=models.Index(condition=models.Q(('moderation_passed', True)), fields=['arena', 'rating'], name='rating_index'),
        ),
        migrations.AddField(
            model_name='arenastats',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors.arena'),
        ),
    ]
