# Generated by Django 4.2.16 on 2024-09-23 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0032_warrior_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warriorarena',
            name='next_battle_schedule_index',
        ),
        migrations.AlterField(
            model_name='warriorarena',
            name='next_battle_schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='warriorarena',
            index=models.Index(condition=models.Q(('moderation_passed', True)), fields=['next_battle_schedule'], name='next_battle_schedule_index'),
        ),
    ]
