# Generated by Django 4.2.16 on 2024-09-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0033_remove_warriorarena_next_battle_schedule_index_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warriorarena',
            name='body_sha_256',
        ),
        migrations.RemoveConstraint(
            model_name='warriorarena',
            name='arena_body_sha_256_unique',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='body',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='body_sha_256',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='moderation_date',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='moderation_model',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='moderation_passed',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='name',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='public_battle_results',
        ),
        migrations.AlterField(
            model_name='warriorarena',
            name='warrior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warrior_arenas', to='warriors.warrior'),
        ),
        migrations.AddConstraint(
            model_name='warriorarena',
            constraint=models.UniqueConstraint(fields=('arena', 'warrior'), name='arena_warrior_unique'),
        ),
    ]
