# Generated by Django 4.2.16 on 2024-09-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0037_alter_warrioruserpermission_warrior'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warrioruserpermission',
            name='warrior_arena_user_unique',
        ),
        migrations.RemoveField(
            model_name='warriorarena',
            name='users',
        ),
        migrations.RemoveField(
            model_name='warrioruserpermission',
            name='warrior_arena',
        ),
    ]
