# Generated by Django 4.2.16 on 2024-10-20 13:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_goals', '0002_goalprogress_message'),
        ('warriors', '0039_textunit_voyage_3_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='voyage_3_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=1024),
        ),
        migrations.AddField(
            model_name='warrior',
            name='voyage_3_embedding_goal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_goals.goal'),
        ),
    ]
