# Generated by Django 4.2.16 on 2024-10-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0040_warrior_voyage_3_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='battle',
            name='warrior_ordering',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='warrior_1',
            new_name='warrior_arena_1',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='warrior_2',
            new_name='warrior_arena_2',
        ),
        migrations.AddConstraint(
            model_name='battle',
            constraint=models.CheckConstraint(condition=models.Q(('warrior_arena_1_id__lt', models.F('warrior_arena_2_id'))), name='warrior_ordering'),
        ),
    ]
