# Generated by Django 4.2.16 on 2024-11-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0041_remove_battle_warrior_ordering_and_more'),
    ]

    operations = [
        # At first "warrior_arena_x" fields were names "warrior_x". This created an index with automatic name.
        # Then the fields were renamed, but indexes were not.
        # We need to rename these indexes to avoid clash with indexes on new "warrior_x" fields.
        migrations.RunSQL(
            sql='ALTER INDEX warriors_battle_warrior_1_id_28976858 RENAME TO warriors_battle_warrior_arena_1_id_28976858',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX warriors_battle_warrior_2_id_e4338512 RENAME TO warriors_battle_warrior_arena_2_id_e4338512',
        ),
        migrations.AddField(
            model_name='battle',
            name='warrior_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warriors.warrior'),
        ),
        migrations.AddField(
            model_name='battle',
            name='warrior_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warriors.warrior'),
        ),
        migrations.RemoveConstraint(
            model_name='battle',
            name='warrior_ordering',
        ),
        migrations.AddConstraint(
            model_name='battle',
            constraint=models.CheckConstraint(check=models.Q(('warrior_1_id__lt', models.F('warrior_2_id'))), name='warrior_ordering'),
        ),
        migrations.AddConstraint(
            model_name='battle',
            constraint=models.CheckConstraint(check=models.Q(('warrior_arena_1_id__lt', models.F('warrior_arena_2_id'))), name='warrior_arena_ordering'),
        ),
    ]
