# Generated by Django 4.2.16 on 2024-11-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0042_auto_20241103_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='warrior_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warriors.warrior'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='warrior_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warriors.warrior'),
        ),
    ]
