# Generated by Django 4.2.16 on 2024-11-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0043_alter_battle_warrior_1_alter_battle_warrior_2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='battle',
            name='warrior_arena_ordering',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='warrior_arena_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='warrior_arena_2',
        ),
    ]
