# Generated by Django 4.2.16 on 2024-11-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0044_remove_battle_warrior_arena_ordering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='prompt',
        ),
    ]
