# Generated by Django 4.2.16 on 2024-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0045_remove_arena_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='llm',
            field=models.CharField(choices=[('openai-gpt', 'OpenAI GPT'), ('claude-3-haiku', 'Claude 3 Haiku')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
