# Generated by Django 4.2.17 on 2025-02-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0047_alter_arena_llm_alter_battle_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='attempts_1_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='attempts_2_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
