# Generated by Django 4.2.19 on 2025-02-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0050_arena_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='arena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warriors.arena'),
        ),
    ]
