# Generated by Django 4.2.19 on 2025-02-23 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0051_alter_battle_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriorarena',
            name='rating_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
