# Generated by Django 4.2.19 on 2025-03-03 01:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_goals', '0009_goal_waiting_for_not_achieved_count'),
        ('warriors', '0052_warriorarena_rating_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('1_2', '1→2'), ('2_1', '2→1')], max_length=3)),
                ('algorithm', models.CharField(choices=[('lcs', 'Longest Common Subsequence'), ('embeddings', 'Embeddings')], max_length=20)),
                ('warrior_1_similarity', models.FloatField(blank=True, help_text='Similarity score between result and warrior 1, in game order.', null=True)),
                ('warrior_2_similarity', models.FloatField(blank=True, help_text='Similarity score between result and warrior 2, in game order.', null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='warriors.battle')),
                ('processed_goal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_goals.goal')),
            ],
            options={
                'indexes': [models.Index(fields=['battle', 'direction', 'algorithm'], name='warriors_ga_battle__5058d4_idx')],
                'unique_together': {('battle', 'direction', 'algorithm')},
            },
        ),
    ]
