# Generated by Django 4.2.19 on 2025-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0053_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='warriors_similarity',
            field=models.FloatField(
                blank=True, help_text='Similarity score between warriors', null=True
            ),
        ),
    ]
