# Generated by Django 5.2.7 on 2025-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0054_gamescore_warriors_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='input_sha256_1_2',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='input_sha256_2_1',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
    ]
