# Generated by Django 5.2.7 on 2025-10-27 19:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_goals', '0011_goalpickup'),
        ('warriors', '0055_battle_input_sha256_1_2_battle_input_sha256_2_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBGame',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'llm',
                    models.CharField(
                        choices=[
                            ('openai-gpt', 'OpenAI GPT'),
                            ('claude-3-haiku', 'Anthropic Claude'),
                            ('google-gemini', 'Google Gemini'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'scheduled_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    'input_sha256',
                    models.BinaryField(blank=True, max_length=32, null=True),
                ),
                ('finish_reason', models.CharField(blank=True, max_length=20)),
                ('llm_version', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                (
                    'processed_goal',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='django_goals.goal',
                    ),
                ),
                (
                    'text_unit',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='warriors.textunit',
                    ),
                ),
                (
                    'warrior_1',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='warriors.warrior',
                    ),
                ),
                (
                    'warrior_2',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='warriors.warrior',
                    ),
                ),
            ],
            options={
                'db_table': 'warriors_game',
            },
        ),
    ]
