# Generated by Django 5.2.13 on 2026-07-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0056_dbgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='lcs_len_1_2_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='lcs_len_1_2_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='lcs_len_2_1_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='lcs_len_2_1_2',
        ),
    ]
