# Generated by Django 5.2.16 on 2026-10-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0061_gamescore_game_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='attempts_1_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='attempts_2_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='finish_reason_1_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='finish_reason_2_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='input_sha256_1_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='input_sha256_2_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='llm_version_1_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='llm_version_2_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='rating_transferred_at',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='resolved_at_1_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='resolved_at_2_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='text_unit_1_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='text_unit_2_1',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='direction',
        ),
    ]
