# Generated by Django 5.2.16 on 2026-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_goals', '0011_goalpickup'),
        ('warriors', '0062_drop_battle_directional_columns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBGame',
            new_name='Game',
        ),
    ]
