from django.template.response import TemplateResponse
from dominate.tags import a, h1, h2, hgroup, li, main, p, section, strong, ul

from djsfc import Router, parse_template


router = Router(__name__)


# Create a template that extends base.html and includes our Dominate-generated content
template = parse_template('''
{% extends "base.html" %}

{% block title %}Privacy Policy - Prompt wars{% endblock %}

{% block content %}
{{ privacy_content|safe }}
{% endblock %}
''', router=router)


@router.route('GET', '')
def root(request):
    main_el = main(cls="container")

    with main_el:
        with hgroup():
            h1("Data Policy")
            p("what we do with your data")

        with section():
            h2("Submitted Warriors")
            p("Your submitted prompts (\"warriors\" or \"spells\") are stored in our database and used in battles.")
            p(strong("Do not include sensitive information"), " in your warriors. Once submitted, they may become visible to other users.")
            p("We currently do not support deleting warriors from our system.")

        with section():
            h2("Battle Results")
            p("Battle results are generated by combining two players' warriors. Please note:")
            with ul():
                li("Battle results are always visible to the other participant in the battle")
                li("If either participant has enabled \"public battle results\", the battle output will be publicly viewable")
                li("We currntly do not support deleting battle results from our system.")

        with section():
            h2("King of the Hill")
            p("What a player writes for the hill stays private to them, with one exception:")
            with ul():
                li(
                    "When a spell takes the hill, its text, the name and author given to it, "
                    "and the model's replies in the battle that won it are published. "
                    "The attack form asks for this consent with every attack.",
                )
                li(
                    "Every other attack's text, the names given to it and the model's replies "
                    "are shown only in the browser session it was sent from.",
                )
                li(
                    "An attack's score is shown without them: "
                    "in the round's standings, as \"Attacker #k\", "
                    "and to anyone who opens the attack's link.",
                )
                li(
                    "The hill tells players apart by a random key in the session cookie. "
                    "Logging out, clearing cookies or two weeks without an attack ends it, "
                    "and with it access to earlier attacks.",
                )
                li("The attack form uses Google reCAPTCHA, which sends the visitor's IP address to Google. The hill stores no IP address.")
                li(
                    "To have a published spell taken down, contact the operator through the project's ",
                    a("GitHub page", href="https://github.com/SupraSummus/prompt-wars"),
                    ".",
                )

    return TemplateResponse(request, template, {
        'privacy_content': main_el.render(),
    })
