from django.template.response import TemplateResponse
from dominate.tags import h1, h2, hgroup, li, main, p, section, strong, ul

from djsfc import Router, parse_template


router = Router(__name__)


# Create a template that extends base.html and includes our Dominate-generated content
template = parse_template('''
{% extends "base.html" %}

{% block title %}Privacy Policy - Prompt wars{% endblock %}

{% block content %}
{{ privacy_content|safe }}
{% endblock %}
''', router=router)


@router.route('GET', '')
def root(request):
    main_el = main(cls="container")

    with main_el:
        with hgroup():
            h1("Data Policy")
            p("what we do with your data")

        with section():
            h2("Submitted Warriors")
            p("Your submitted prompts (\"warriors\" or \"spells\") are stored in our database and used in battles.")
            p(strong("Do not include sensitive information"), " in your warriors. Once submitted, they may become visible to other users.")
            p("We currently do not support deleting warriors from our system.")

        with section():
            h2("Battle Results")
            p("Battle results are generated by combining two players' warriors. Please note:")
            with ul():
                li("Battle results are always visible to the other participant in the battle")
                li("If either participant has enabled \"public battle results\", the battle output will be publicly viewable")
                li("We currntly do not support deleting battle results from our system.")

    return TemplateResponse(request, template, {
        'privacy_content': main_el.render(),
    })
